---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ17N18" #see SAP Continuous Integration and Delivery service for more build tool version options
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Malware Scan:
    malwareExecuteScan: true
  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "develop_develop-6utlm28t"
    cfSpace: "dev"
    cfAppName: "Incident-Management"
    cfCredentialsId: "cf-credentails"
    deployType: "standard"
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "develop_develop-6utlm28t"
    cfSpace: "dev"
    cfAppName: "Incident-Management"
    cfCredentialsId: "cf-credentails"
    deployType: "standard"
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint:
    failOnError: true
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "trail"
    credentialsId: "sk-ctms"
